const cardsText = [
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardOne',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardTwo',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardThree',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardFour',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardFive',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardSix',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardSeven',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardEight',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardNine',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardTen',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardEleven',
    },
    {
        imageAltOne: '',
        imageAltTwo: '',
        imageAltThree: '',
        location: 'San Salvatore Monferrato, Italia',
        rating: '4,91',
        host: 'Mauro',
        date: '31 gen - 05 feb',
        price: '188 €',
        ID: 'cardTwelve',
    },
];

const cardsImages = [
    {
        image: 'https://a0.muscache.com/im/pictures/17979331/3f134177_original.jpg?im_w=720&im_format=avif',
    },
    {
        image: 'https://a0.muscache.com/im/pictures/17979343/76ca328a_original.jpg?im_w=720&im_format=avif',
    },
    {
        image: 'https://a0.muscache.com/im/pictures/17979357/c94cb06d_original.jpg?im_w=720&im_format=avif',
    },
];
